title: Salim Perchy
email: yamil-salim.perchy@inria.fr
description: >
  Website of R&D engineer Salim Perchy
# set to website root address when deploying (e.g., "https://members.loria.fr/sperchy")
baseurl: "https://members.loria.fr/sperchy"
url: "https://members.loria.fr"

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
markdown: kramdown
